---
title: "Single-constrained SIMs"
output: html_notebook
---

```{r}
# Load required libraries and files
library(spatstat)
library(rgeos)
library(maptools)
library(GISTools)
library(rgdal)
library(spdep)
library(tidyverse)
library(sf)
library(tmap)
library(tmaptools)
library(sp)
library(reshape2)
library(stplanr)

# Read in the Westminster OA shapefile as SP object
West <- readOGR("Westminster OA Full Data_shapefile.shp")

# Read the sportcentres shapefile that has locations
sportcentres <- readOGR("Sportcentres_locations.shp")

# Import the spatial interaction data that was prepared and transformed in Python
mdata <- read_csv("Spatial Interaction Data_v2.csv",col_names = TRUE)

# Create functions to calculate r2 and RMSE
CalcRSquared <- function(observed,estimated){
  r <- cor(observed,estimated)
  R2 <- r^2
  R2
}

CalcRMSE <- function(observed,estimated){
  res <- (observed - estimated)^2
  RMSE <- round(sqrt(mean(res)),3)
  RMSE
}

# Single-constrained models testing the influence of Acorn classifications.
# Test Acorn CATEGORY
# Constrained by Acorn category. Keep Destination constraint, but add other info.

# Convert categories to 'factor' data type to adjust contrasts
mdata$AcCategory <- as.factor(mdata$AcCategory)
mdata$AcCategoryGr <- as.factor(mdata$AcCategoryGr)
mdata$AcCategoryTy <- as.factor(mdata$AcCategoryTy)

# Manually adjust contrasts to view other control groups
#mdata$AcCategory <- relevel(mdata$AcCategory, ref="Affluent Achiever")

attrSim_acorn <- glm(Users ~ SportsCentre + AcCategory + log(Distance)-1, na.action = na.exclude, family = poisson(link = "log"), data = mdata)


# look at it's summary
options(max.print=1000000)
summary(attrSim_acorn)
```
```{r}
# Print summary results to a text file
#sink('AcornCat-results.txt')
#print(summary(attrSim_acorn))
#sink()

# make estimates and round them 
mdata$attrsimFitted_acorn <- round(fitted(attrSim_acorn),0)

# Put the coefficient values into a dataframe
AcornCatCoefs <- as.data.frame(summary(attrSim_acorn)$coefficients)

# create matrix of predictions
mdatasubmat10 <- dcast(mdata, OA11CD ~ SportsCentre, sum, value.var = "attrsimFitted_acorn", margins=c("OA11CD", "SportsCentre"))

# calculate some goodness-of-fit statistics
CalcRSquared(mdata$Users,mdata$attrsimFitted_acorn)
CalcRMSE(mdata$Users,mdata$attrsimFitted_acorn)

# Write the coefficients to CSV for future use
#write.csv(AcornCatCoefs, "SIM_AcornCat_Coefficients_2.csv")
```
```{r}
# Test Acorn GROUP
# Constrained by Acorn Group. Keep Destination constraint (attraction model), but add Acorn info.

# Manually adjust contrasts
#mdata$AcCategoryGr <- relevel(mdata$AcCategoryGr, ref="Career Climbers")

attrSim_acornGR <- glm(Users ~ SportsCentre + AcCategoryGr + log(Distance)-1, na.action = na.exclude, family = poisson(link = "log"), data = mdata)


# look at summary
summary(attrSim_acornGR)
```
```{r}
# Print summary results to a text file
#sink('AcornGr-results.txt')
#print(summary(attrSim_acornGR))
#sink()

# make estimates and round them
mdata$attrsimFitted_acornGR <- round(fitted(attrSim_acornGR),0)

# Put the coefficient values into a dataframe
AcornGroupCoefs <- as.data.frame(summary(attrSim_acornGR)$coefficients)

# create matrix of predictions
mdatasubmat11 <- dcast(mdata, OA11CD ~ SportsCentre, sum, value.var = "attrsimFitted_acornGR", margins=c("OA11CD", "SportsCentre"))

# calculate some goodness-of-fit statistics
CalcRSquared(mdata$Users,mdata$attrsimFitted_acornGR)
CalcRMSE(mdata$Users,mdata$attrsimFitted_acornGR)

# Write the coefficients to CSV for future use
#write.csv(AcornGroupCoefs, "SIM_AcornGr_Coefficients.csv")

```
```{r}
# Finally, Test Acorn TYPE
# Constrained by Acorn Type. Keep Destination constraint (attraction model), but add other info.

# manually adjust contrasts
#mdata$AcCategoryTy <- relevel(mdata$AcCategoryTy, ref="Younger professionals in smaller flats")

attrSim_acornTY <- glm(Users ~ SportsCentre + AcCategoryTy + log(Distance)-1, na.action = na.exclude, family = poisson(link = "log"), data = mdata)

# look at summary
summary(attrSim_acornTY)
```
```{r}
# Print summary results to a text file
#sink('AcornTy-results.txt')
#print(summary(attrSim_acornTY))
#sink()

# make estimates and round them round the estimates
mdata$attrsimFitted_acornTY <- round(fitted(attrSim_acornTY),0)

# Put the coefficient values into a dataframe
AcornTypeCoefs <- as.data.frame(summary(attrSim_acornTY)$coefficients)

# Create matrix of predictions
mdatasubmat12 <- dcast(mdata, OA11CD ~ SportsCentre, sum, value.var = "attrsimFitted_acornTY", margins=c("OA11CD", "SportsCentre"))

# calculate some goodness-of-fit statistics
CalcRSquared(mdata$Users,mdata$attrsimFitted_acornTY)
CalcRMSE(mdata$Users,mdata$attrsimFitted_acornTY)

# Write the coefficients to CSV for future use
#write.csv(AcornTypeCoefs, "SIM_AcornTy_Coefficients.csv")
```

