---
title: "Autocorrelation and LISA"
output: html_notebook
---

```{r}
# Load in the libraries for use
library(spatstat)
library(sp)
library(rgeos)
library(maptools)
library(GISTools)
library(geojsonio)
library(tmaptools)
library(rgdal)
library(spdep)
library(tidyverse)
library(tmap)
library(sf)

#read the Wesminster OA shapefile that has our attributes
WestminOA <- readOGR("Westminster OA Full Data_shapefile.shp")

#read the sportcentres shapefile that has locations
sportcentres <- readOGR("Sportcentres_locations.shp")

# Ensure they are projected as BNG
proj4string(WestminOA) <- CRS("+init=epsg:27700")
proj4string(sportcentres) <- CRS("+init=epsg:27700")

# Plot it with a choropleth of usage rates
tm_shape(WestminOA) +
tm_polygons("UsageRate",
        style="jenks",
        palette="PuRd",
        title="Usage Rate (%)")+
tm_shape(sportcentres) +
    tm_symbols(col = "yellow", size = 0.3)+
tm_layout(title = "Westminster \nSport Centre \nUsage Rate",
          title.position = c("right", "top"),
          legend.title.size = 1,
          legend.text.size = 0.8)
```
```{r}
# Create boxplot of our Usage Rate data

boxplot(WestminOA@data$UsageRate,
main = "OA SC Usage Rate In Westminster Borough",
xlab = "Usage Rate (%)",
ylab = "OA",
col = "magenta",
border = "black",
horizontal = TRUE
)
text(x = boxplot.stats(WestminOA@data$UsageRate)$stats, labels = boxplot.stats(signif(WestminOA@data$UsageRate, digits=3))$stats, y = 1.25, cex = 0.55)


```
```{r}
# Investigate autocorrelations with Global Morans I. First must calculate a spatial weights matrix for Morans I

# Import OA Centroids calculated and fixed in QGIS.
coordsWOA <- readOGR("Westminster_OA_FixedCentroids.shp")
proj4string(coordsWOA) <- CRS("+init=epsg:27700")
coordsWOA <- coordinates(coordsWOA)

# Create a binary matrix of queen's case neighbours
# Create the neighbours list, using Queen's case.
WestOA_nb <- poly2nb(WestminOA, queen=TRUE)

#plot them with map underneath
plot(WestOA_nb, coordinates(coordsWOA), col="red") + plot(WestminOA,add=T)

```
```{r}
# Create the spatial weights object.
WOA.lw <- nb2listw(WestOA_nb, style="C")

# With weight matrix created, calculate Global Morans I and other autocorrelation statistics

# Moran's I test for Usage Rate - tells us whether we have clustered values (close to 1) or dispersed values (close to -1)

Moran_WOA_Global_Density <- moran.test(WestminOA@data$UsageRate, WOA.lw)
Moran_WOA_Global_Density
```

```{r}
# Create the Moran I scatterplot

moran.plot(WestminOA@data$UsageRate, WOA.lw,main = "Global Moran's I Scatterplot", xlab="SC Usage Rate", ylab="Spatially Lagged SC Usage Rate", labels=WestminOA@data$OA11CD)

```
```{r}
# Perform Geary's C test. Tells whether similar values or dissimilar values are clusering
Geary_WOA_Global_Density <- geary.test(WestminOA@data$UsageRate, WOA.lw)
Geary_WOA_Global_Density
```
```{r}
# Perform Getis Ord General G test. Tells whether high or low values are clustering. If G > Expected = High values clustering; if G < expected = low values clustering
Getis_WOA_Global_Density <- globalG.test(WestminOA@data$UsageRate, WOA.lw)
Getis_WOA_Global_Density
```

```{r}
# With global autocorrelation tests complete, can now compute LISAs

# Can calculate local versions of the Morans I statistic (for each OA) and Getis Ord Gi* statistic to see where we have hot-spots

# Use localmoran() function to generate Moran's I for each OA in Westminster
Morans_WOA_Local_Density <- localmoran(WestminOA@data$UsageRate, WOA.lw)

# We require the I score (column 1) and the z-score standard deviation (column 4) scores.
WestminOA@data$BLocIR <- Morans_WOA_Local_Density[,1]
WestminOA@data$BLocIRz <- Morans_WOA_Local_Density[,4]

# Plot the outputs of Local Moran's I

# Set breaks manually based on the rule that data points >2.58 or <-2.58 standard deviations away from the mean are significant at the 99% level (<1% chance that autocorrelation not present); >1.96 - <2.58 or <-1.96 to >-2.58 standard deviations are significant at the 95% level (<5% change that autocorrelation not present). >1.65 = 90% etc.
breaks1<-c(-1000,-2.58,-1.96,-1.65,1.65,1.96,2.58,1000)


# Plot the Local Moran's I map
tm_shape(WestminOA) +
    tm_polygons("BLocIRz",
        breaks=breaks1,
        palette='RdBu',
        midpoint=NA,
        title="Standard Deviations",
        labels=c("<-2.58","-2.58 to -1.96","-1.96 to - 1.65","-1.65 to 1.65","1.65 to 1.96","1.96 to 2.58",">2.58")) +
tm_shape(sportcentres) +
    tm_symbols(col = "yellow", size = 0.3)+
tm_layout(title = "Local Moran's I \nResults of \nSC Usage",
          title.position = c("right", "top"),
          legend.title.size = 1,
          legend.text.size = 0.8)
```
```{r}
# Next, calculate Getis Ord Gi* statistic to see where we have hot-spots

Gi_WOA_Local_Density <- localG(WestminOA@data$UsageRate, WOA.lw)

# Add the z-score (standardised value relating to whether high values or low values are clustering together) to our WestminOA SP dataframe
WestminOA@data$BLocGiRz <- Gi_WOA_Local_Density

# Plot the Getis Ord G*i map. Uses are same breaks as local Morans I.
tm_shape(WestminOA) +
    tm_polygons("BLocGiRz",
        breaks=breaks1,
        palette='RdBu',
        midpoint=NA,
        title="Standard Deviations",
        labels=c("<-2.58","-2.58 to -1.96","-1.96 to - 1.65","-1.65 to 1.65","1.65 to 1.96","1.96 to 2.58",">2.58")) +
tm_shape(sportcentres) +
    tm_symbols(col = "yellow", size = 0.3)+
tm_layout(title = "Getis Ord Gi* \nResults of \nSC Usage",
          title.position = c("right", "top"),
          legend.title.size = 1,
          legend.text.size = 0.8)
```

