---
title: "Double-constrained SIM"
output: html_notebook
---

```{r}
# Load required libraries and files
library(spatstat)
library(rgeos)
library(maptools)
library(GISTools)
library(rgdal)
library(spdep)
library(tidyverse)
library(sf)
library(tmap)
library(tmaptools)
library(sp)
library(reshape2)
library(stplanr)

# Read in the Westminster OA shapefile as SP object
West <- readOGR("Westminster OA Full Data_shapefile.shp")

# Read the sportcentres shapefile that has locations
sportcentres <- readOGR("Sportcentres_locations.shp")

# Import the spatial interaction data that was prepared and transformed in Python
mdata <- read_csv("Spatial Interaction Data_v2.csv",col_names = TRUE)

# Create functions to calculate r2 and RMSE
CalcRSquared <- function(observed,estimated){
  r <- cor(observed,estimated)
  R2 <- r^2
  R2
}

CalcRMSE <- function(observed,estimated){
  res <- (observed - estimated)^2
  RMSE <- round(sqrt(mean(res)),3)
  RMSE
}

# Run the double-constrained SIM.
doubSim <- glm(Users ~ OA11CD+SportsCentre+log(Distance), na.action = na.exclude, family = poisson(link = "log"), data = mdata)

#look at it's summary
options(max.print=1000000)
summary(doubSim)
```
```{r}

# Print summary results to a text file
#sink('doubSim-results.txt')
#print(summary(doubSim))
#sink()

# Make estimates and them
mdata$doubsimFitted <- round(fitted(doubSim),0)

# Put the coefficient values into a dataframe
DoubSIMCoefs <- as.data.frame(summary(doubSim)$coefficients)

# Create matrix of predictions
mdatasubmat5 <- dcast(mdata, OA11CD ~ SportsCentre, sum, value.var = "doubsimFitted", margins=c("OA11CD", "SportsCentre"))

# Write matrix to CSV
#write.csv(mdatasubmat5, file = "doubSIM-estimates.csv")

#use the functions from the last practical to calculate some goodness-of-fit statistics
CalcRSquared(mdata$Users,mdata$doubsimFitted)
CalcRMSE(mdata$Users,mdata$doubsimFitted)

# Write the coefficients to CSV for future use
#write.csv(DoubSIMCoefs, "SIM_DoubSIM_Coefficients.csv")
```
```{r}
# Use predictions from model to generate a residual matrix. Shows us how the model does predicting the number of users by OA to each SC.

# In main dataframe we've been using, calculate the residuals by subtracting the estimates from the actual, and keep only that column
mdata$doubSIMresiduals <- mdata$doubsimFitted - mdata$Users

# Convert this new residual column to a matrix
mdata_DSIM_resmatrix <- dcast(mdata, OA11CD ~ SportsCentre, sum, value.var = "doubSIMresiduals", margins=c("OA11CD", "SportsCentre"))

# Merge our residual matrix to SP object by OA
West_res <- merge(West,mdata_DSIM_resmatrix, by="OA11CD")

# Create scatterplot of the residuals (y) vs distance (x)
# Shows that most errors are made at close distance

qplot(mdata$Distance, mdata$doubSIMresiduals, main = "Double-Constrained SIM Residuals by Distance", xlab="Distance (metres)", ylab="Residuals") + theme_bw() + theme(plot.title = element_text(hjust = 0.5))
```

```{r}
# Map the residuals of each SC

# Jubilee SC
tm_shape(West_res) +
tm_polygons("Jubilee SC",
        style="cont",
        palette="RdBu",
        title="Residuals") +
tm_shape(sportcentres[sportcentres@data$Location=="Jubilee Sports Centre",]) +
    tm_symbols(col = "yellow", size = 0.3)+
tm_layout(title = "Jubilee SC \nSIM Residuals",
          title.position = c("right", "top"),
          legend.title.size = 1,
          legend.text.size = 0.8)
```
```{r}
# Porchester Hall
tm_shape(West_res) +
tm_polygons("Porchester Hall",
        style="cont",
        palette="RdBu",
        title="Residuals")+
tm_shape(sportcentres[sportcentres@data$Location=="Porchester Hall",]) +
    tm_symbols(col = "yellow", size = 0.3)+
tm_layout(title = "Porchester Hall \nSIM Residuals",
          title.position = c("right", "top"),
          legend.title.size = 1,
          legend.text.size = 0.8)
```

```{r}
# Little Venice
tm_shape(West_res) +
tm_polygons("Little Venice SC",
        style="cont",
        palette="RdBu",
        title="Residuals")+
tm_shape(sportcentres[sportcentres@data$Location=="Little Venice Sports Centre",]) +
    tm_symbols(col = "yellow", size = 0.3)+
tm_layout(title = "Little Venice SC \nSIM Residuals",
          title.position = c("right", "top"),
          legend.title.size = 1,
          legend.text.size = 0.8)
```

```{r}
# Seymour
tm_shape(West_res) +
tm_polygons("Seymour LC",
        style="cont",
        palette="RdBu",
        title="Residuals")+
tm_shape(sportcentres[sportcentres@data$Location=="Seymour Leisure Centre",]) +
    tm_symbols(col = "yellow", size = 0.3)+
tm_layout(title = "Seymour LC \nSIM Residuals",
          title.position = c("right", "top"),
          legend.title.size = 1,
          legend.text.size = 0.8)
```

```{r}
# Queen Mother
tm_shape(West_res) +
tm_polygons("Queen Mother SC",
        style="cont",
        palette="RdBu",
        title="Residuals")+
tm_shape(sportcentres[sportcentres@data$Location=="Queen Mother Sports Centre",]) +
    tm_symbols(col = "yellow", size = 0.3)+
tm_layout(title = "Queen Mother SC \nSIM Residuals",
          title.position = c("right", "top"),
          legend.title.size = 1,
          legend.text.size = 0.8)
```

```{r}
# Marshall Street
tm_shape(West_res) +
tm_polygons("Marshall Street LC",
        style="cont",
        palette="RdBu",
        title="Residuals")+
tm_shape(sportcentres[sportcentres@data$Location=="Marshall Street Leisure Centre",]) +
    tm_symbols(col = "yellow", size = 0.3)+
tm_layout(title = "Marshall Street LC \nSIM Residuals",
          title.position = c("right", "top"),
          legend.title.size = 1,
          legend.text.size = 0.8)
```

```{r}
# Moberly
tm_shape(West_res) +
tm_polygons("Moberly SC",
        style="cont",
        palette="RdBu",
        title="Residuals")+
tm_shape(sportcentres[sportcentres@data$Location=="Moberly Sports Centre",]) +
    tm_symbols(col = "yellow", size = 0.3)+
tm_layout(title = "Moberly SC \nSIM Residuals",
          title.position = c("right", "top"),
          legend.title.size = 1,
          legend.text.size = 0.8)

```

```{r}
# Paddington Rec Ground
tm_shape(West_res) +
tm_polygons("Paddington Rec Ground",
        style="cont",
        palette="RdBu",
        title="Residuals")+
tm_shape(sportcentres[sportcentres@data$Location=="Paddington Recreation Ground",]) +
    tm_symbols(col = "yellow", size = 0.3)+
tm_layout(title = "Paddington \nRec Ground \nSIM Residuals",
          title.position = c("right", "top"),
          legend.title.size = 1,
          legend.text.size = 0.8)
```

