---
title: "Misc Charts and Maps"
output: html_notebook
---

```{r}
# Import required libraries and files
library(spatstat)
library(sp)
library(rgeos)
library(maptools)
library(GISTools)
library(tmaptools)
library(rgdal)
library(spdep)
library(tidyverse)
library(tmap)
library(sf)

#read the Wesminster OA shapefile that has our attributes
WestminOA <- readOGR("Westminster OA Full Data_shapefile.shp")

#read the sportcentres shapefile that has locations
sportcentres <- readOGR("Sportcentres_locations.shp")

# Read in nearest sport centre CSV file
close_SC <- read_csv("OA_nearest SC distance.csv",col_names = TRUE)

# Join new data with WestminOA shapefile
WestminOA = merge(WestminOA,close_SC,by = "OA11CD")


# Map OAs by their nearest sport centre
# Plot the map coloured by nearest SC
tm_shape(WestminOA) +
    tm_polygons("HubName",
        title="Sport Centre")+
tm_shape(sportcentres) +
    tm_symbols(col = "yellow", size = 0.3)+
   tm_layout(main.title = "Nearest Sport Centre by Euclidean Distance", main.title.size = 1.2,main.title.position="center")+
    tm_scale_bar(size = 0.7, position = c("right", "top"))+
  tm_compass(type = "4star", position = c(0.75, 0.65))


```

```{r}
# Histogram of the nearest distances to show average distance to nearest SC

qplot(WestminOA@data$HubDist, main = 'Distances to Nearest Sport Centre', ylab = 'Frequency', xlab = 'Distance (metres)') + 
  geom_histogram(col='white', fill='black')+
  geom_vline(xintercept=mean(WestminOA@data$HubDist),colour="red",	size=1, linetype = "longdash") + 
  annotate("text",	x=950,	y=85,	label="Mean: 644.66 metres", col='red', size = 3.5)+
  geom_segment(aes(x=quantile(WestminOA@data$HubDist, 0.25), xend=quantile(WestminOA@data$HubDist, 0.25), y = 0, yend=80), color='blue', size =1)+ 
  annotate("text",	x=165,	y=83,	label="1st Quartile: 402.23 metres", col='blue', size=3.5)+
 geom_segment(aes(x=quantile(WestminOA@data$HubDist, 0.75), xend=quantile(WestminOA@data$HubDist, 0.75), y = 0, yend=80), color='blue', size =1)+
  annotate("text",	x=1200,	y=70,	label="3rd Quartile: 822.65 metres", col='blue', size = 3.5)+
  theme_bw() + 
  theme(plot.title = element_text(hjust = 0.5))
```

```{r}
# Map the sport centres

tm_shape(WestminOA) +
  tm_borders(col='grey')+
    tm_shape(sportcentres[sportcentres@data$Location=="Seymour Leisure Centre",]) +
    tm_symbols(col = "yellow", size = 0.3)+
     tm_text("Location", size = 0.8, ymod = -0.5, xmod = 1.8)+
  tm_shape(sportcentres[sportcentres@data$Location=="Porchester Hall",]) +
    tm_symbols(col = "yellow", size = 0.3)+
     tm_text("Location", size = 0.8, ymod = -0.5)+
tm_shape(sportcentres[sportcentres@data$Location=="Jubilee Sports Centre",]) +
    tm_symbols(col = "yellow", size = 0.3)+
     tm_text("Location", size = 0.8, ymod = -0.5, xmod = 1.7)+
tm_shape(sportcentres[sportcentres@data$Location=="Little Venice Sports Centre",]) +
    tm_symbols(col = "yellow", size = 0.3)+
     tm_text("Location", size = 0.8, ymod = 0.5, xmod = 4.5)+
  tm_shape(sportcentres[sportcentres@data$Location=="Marshall Street Leisure Centre",]) +
    tm_symbols(col = "yellow", size = 0.3)+
     tm_text("Location", size = 0.8, ymod = -0.5)+
  tm_shape(sportcentres[sportcentres@data$Location=="Moberly Sports Centre",]) +
    tm_symbols(col = "yellow", size = 0.3)+
     tm_text("Location",size = 0.8, ymod = 0.8, xmod = 3)+
  tm_shape(sportcentres[sportcentres@data$Location=="Paddington Recreation Ground",]) +
    tm_symbols(col = "yellow", size = 0.3)+
     tm_text("Location", size = 0.8, ymod = -0.2, xmod = 5)+
  tm_shape(sportcentres[sportcentres@data$Location=="Queen Mother Sports Centre",]) +
    tm_symbols(col = "yellow", size = 0.3)+
     tm_text("Location", size = 0.8, ymod = -0.5)+
  tm_layout(main.title = "Westminster Sport and Leisure Centres", title.size = 1.5,main.title.position="center")+
    tm_compass(type = "4star", position = c("right", "top")) +
  tm_scale_bar(size = 0.7, position = c("left", "bottom"))
```

```{r}
# Map the OA geodemographic by category

# Set colour pallete
Mypal <- c('blue','orange','grey','orchid3','skyblue')

tm_shape(WestminOA) +
    tm_polygons("AcCategory",
        palette=Mypal,
        title="Geodemographic Category", colorNA = 'white')+
tm_shape(sportcentres) +
    tm_symbols(col = "yellow", size = 0.3)+
tm_layout(title = "Westminster's \nAcorn \nGeodemographics\n     - Category",
          title.position = c("right", "top"),
          legend.title.size = 1,
          legend.text.size = 0.8)
```
```{r}
# Map the OA geodemographic by group

tm_shape(WestminOA) +
    tm_polygons("AcCatego_2",
        title="Geodemographic Group", colorNA = 'white')+
tm_shape(sportcentres) +
    tm_symbols(col = "yellow", size = 0.3)+
tm_layout(title = "Westminster's \nAcorn \nGeodemographics\n     - Group",
          title.position = c("right", "top"),
          legend.title.size = 1,
          legend.text.size = 0.8)
```

